costumes/urls.py
from django.urls import path

from . import views, views_managment

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.index, name='gallery'),
    path('logout', views.logout_page, name='logout_page'),
    path('login', views.login_page, name='login'),
    path('login/script', views.login_script, name='login'),
    path('register', views.register, name='register'),
    path('register/script', views.register_script, name='register'),
    path('edit_user', views.edit_user, name='edit_user'),
    path('edit_user/script', views.edit_user_script, name='edit_user'),
    path('user_change_password', views.change_password, name='edit_user'),
    path('user_change_password/script', views.change_password_script, name='edit_user'),

    path('manage_employee', views_managment.manage_employee, name='manage_employee'),
    path('manage_manager', views_managment.manage_manager, name='manage_manager'),

    path('edit_manager/<int:manager_id>', views_managment.edit_manager, name='manage_manager'),
    path('edit_manager/script', views_managment.edit_manager_script, name='manage_manager'),
    path('create_manager', views_managment.create_manager, name='manage_manager'),
    path('create_manager/script', views_managment.create_manager_script, name='manage_manager'),
    path('delete_manager', views_managment.delete_manager, name='manage_manager'),

    path('edit_employee/<int:employee_id>', views_managment.edit_employee, name='manage_employee'),
    path('edit_employee/script', views_managment.edit_employee_script, name='manage_employee'),
    path('create_employee', views_managment.create_employee, name='manage_employee'),
    path('create_employee/script', views_managment.create_employee_script, name='manage_employee'),
    path('delete_employee', views_managment.delete_employee, name='manage_employee'),

    path('costumes/<int:costume_id>', views.costumes, name='costumes'),
    path('costumes/<int:costume_id>/edit', views.costumes_edit, name='costumes_edit'),
    path('costumes/<int:costume_id>/delete', views.costumes_delete, name='costumes_delete'),
    path('add_costume', views.add_costume.as_view(success_url='/gallery'), name='add_costume'),
    path('add_costume_template', views.add_costume_template.as_view(success_url='/costume_templates'), name='add_costume_template'),

    path('accessories/<int:accessory_id>', views.accessories, name='accessories'),
    path('accessories/<int:accessory_id>/edit', views.accessories_edit, name='accessories_edit'),
    path('accessories/<int:accessory_id>/delete', views.accessories_delete, name='accessories_delete'),
    path('add_accessory', views.add_accessory.as_view(success_url='/gallery'), name='add_accessory'),

    path('borrowings', views.borrowings_gallery, name='borrowings_gallery'),
    path('borrowings/<int:borrowing_id>', views.borrowings, name='borrowing'),
    path('borrowings/<int:borrowing_id>/edit', views.borrowings_edit, name='borrowing_edit'),
    path('borrowings/<int:borrowing_id>/delete', views.borrowings_delete, name='borrowing_delete'),

    path('costume_templates', views.costume_templates_gallery, name='costume_templates_gallery'),
    path('costume_templates/<int:ct_id>', views.costume_templates, name='costume_templates'),
    path('costume_templates/<int:costume_template_id>/edit', views.costume_templates_edit, name='costume_templates_edit'),
    path('costume_templates/<int:costume_template_id>/delete', views.costume_templates_delete, name='costume_templates_delete'),

    path('stores', views.stores_gallery, name='stores_gallery'),
    path('add_store', views.add_store.as_view(success_url='/gallery'), name='add_store'),
    path('stores/<int:store_id>', views.stores, name='stores'),
    path('stores/<int:store_id>/edit', views.stores_edit, name='stores_edit'),
    path('stores/<int:store_id>/delete', views.stores_delete, name='stores_delete'),

    path('add_costume_to_basket', views.add_costume_to_basket, name='add_costume_to_basket'),
    path('add_accessory_to_basket', views.add_accessory_to_basket, name='add_accessory_to_basket'),
    path('remove_costume_from_basket', views.remove_costume_from_basket, name='remove_costume_from_basket'),
    path('remove_accessory_from_basket', views.remove_accessory_from_basket, name='remove_accessory_from_basket'),
    path('finish_borrowing', views.finish_borrowing, name='finish_borrowing'),
    path('user_borrowings', views.user_borrowings, name='user_borrowings'),
    path('user_detail/<int:user_id>', views.user_detail, name='user_detail'),
    path('basket', views.basket, name='basket'),
    path('show_user', views.show_user, name='show_user'),
    path('delete_user/<int:user_id>', views.delete_user, name='delete_user')
]

iis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('costumes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

costumes/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

# pobocka
class Store(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    num = models.CharField(max_length=100)
    opened_from = models.CharField(max_length=5, default='08:00')
    opened_to = models.CharField(max_length=5, default='18:00')

    def __str__(self):
        return 'Store = ' + ' street: ' + self.street + ' city: ' + self.city + ' opened_from: ' + self.opened_from + ' opened_to: ' + self.opened_to

# vzor_kostymu
class CostumeTemplate(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    material = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return 'CostumeTemplate = ' + ' name: ' + self.name + ' manufacturer: ' + self.manufacturer + ' material: ' + self.material + ' description: ' + self.description

# doplnok
class Accessory(models.Model):
    name = models.CharField(max_length=100)
    manufactured = models.DateField('date created')
    description = models.CharField(max_length=500)
    picture = models.ImageField(upload_to='accessory_images/', default='default_images/default.png')
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)], default=1)
    belongs_to_costume = models.ManyToManyField(CostumeTemplate, blank=True)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)

    def __str__(self):
        return 'Accessory = ' + ' name: ' + self.name + ' manufactured: ' + str(self.manufactured) + ' description: ' + self.description + ' price: ' + str(self.price)

# klient
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=100)
    tel_num = models.CharField(max_length=15)

    def __str__(self):
        return 'Customer = ' +  ' address: ' + self.address + ' tel_num: ' + self.tel_num

# zamestnanec
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=100)
    tel_num = models.CharField(max_length=15)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Employee = ' +  ' address: ' + self.address + ' tel_num: ' + self.tel_num

# spravca
class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=100)
    tel_num = models.CharField(max_length=15)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Manager = ' +  ' address: ' + self.address + ' tel_num: ' + self.tel_num

# kostym
class Costume(models.Model):
    COSTUME_SIZE = (
        ('XS', 'XS - Extra Small'),
        ('S', 'S - Small'),
        ('M', 'M - Medium'),
        ('L', 'L - Large'),
        ('XL', 'XL - Extra Large'),
        ('XXL', 'XXL - Extra Extra Large'),
    )
    color = models.CharField(max_length=100)
    size = models.CharField(max_length=3, choices=COSTUME_SIZE)
    manufactured = models.DateField('date created')
    wear_out = models.CharField(max_length=100)
    employee_manage = models.ForeignKey(Employee, on_delete=models.CASCADE)
    costume_template = models.ForeignKey(CostumeTemplate, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='costume_images/', default='default_images/default.png')
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)], default=1)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)

    def __str__(self):
        return 'Costume = ' + ' color: ' + self.color + ' size: ' + self.size + ' manufactured: ' + str(self.manufactured) + ' wear_out: ' + self.wear_out + ' employee_manage: ' + str(self.employee_manage) + ' costume_template: ' + str(self.costume_template) + ' store: ' + str(self.store)

# vypozicka
class Borrowing(models.Model):
    event = models.CharField(max_length=100, blank=True)
    borrowed_date = models.DateField('time borrowed')
    return_date = models.DateField('date to return', blank=True, null=True)
    borrowing_expiration = models.DurationField('borrowed for duration')
    final_price = models.IntegerField(default=0)
    employee_borrowed = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    costume = models.ManyToManyField(Costume, blank=True)
    accessory = models.ManyToManyField(Accessory, blank=True)

    # Handling empty borrowing
    def clean(self):
        # Recursion error
        # if not (self.costume or self.accessory):
            # raise ValidationError('You must specify either accessory or costume for borrowing.')
        # TODO: Check if at least one costume or accessory is present
        # TODO: Check if borrowed_date < return_date
        # Those checks are neccessary for the edit form
        pass

    def __str__(self):
        return 'Borrowing = ' + ' borrowed_date: ' + str(self.borrowed_date) + ' return_date: ' + str(self.return_date) + ' borrowing_expiration: ' + str(self.borrowing_expiration) + ' final_price: ' + str(self.final_price) + ' employee_borrowed: ' + str(self.employee_borrowed) + ' customer: ' + str(self.customer)

costumes/forms.py
from django import forms
from django.forms import ModelForm, DateInput, Form, PasswordInput
from django.contrib.auth.models import User

from .models import *

class LoginForm(Form):
    login = forms.CharField(label='login', max_length=100)
    password = forms.CharField(label='password', max_length=100)

class BorrowingForm(ModelForm):
    class Meta:
        model = Borrowing
        fields = '__all__'
        widgets = {
            'borrowed_date': DateInput(attrs={'type': 'date'}),
            'return_date': DateInput(attrs={'type': 'date'}),
        }

class CostumeTemplateForm(ModelForm):
    class Meta:
        model = CostumeTemplate
        fields = '__all__'

class CostumeForm(ModelForm):
    class Meta:
        model = Costume
        fields = '__all__'
        widgets = {
            'manufactured': DateInput(attrs={'type': 'date'}),
        }

class AccessoryForm(ModelForm):
    class Meta:
        model = Accessory
        fields = '__all__'
        widgets = {
            'manufactured': DateInput(attrs={'type': 'date'}),
        }

class StoreForm(ModelForm):
    class Meta:
        model = Store
        fields = '__all__'

class RegisterForm(Form):
    first_name = forms.CharField(label='firs_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    login = forms.CharField(label='login', max_length=50)
    email = forms.CharField(label='email', max_length=50, required=False)
    password = forms.CharField(label='password_1', max_length=50, min_length=6)

class EditManagerForm(Form):
    id = forms.CharField(label='id', max_length=50)
    first_name = forms.CharField(label='first_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    email = forms.CharField(label='email', max_length=50, required=False)
    address = forms.CharField(label='address', max_length=100, required=False)
    tel_num = forms.CharField(label='tel_num', max_length=15, required=False)
    store = forms.CharField(label='store', max_length=50, required=False)
    super_manager = forms.CharField(label='super_manager', max_length=50, required=False)

class CreateManagerForm(Form):
    login = forms.CharField(label='login', max_length=50)
    password = forms.CharField(label='password', max_length=50, min_length=6)
    first_name = forms.CharField(label='first_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    email = forms.CharField(label='email', max_length=50, required=False)
    address = forms.CharField(label='address', max_length=100, required=False)
    tel_num = forms.CharField(label='tel_num', max_length=15, required=False)
    store = forms.CharField(label='store', max_length=50, required=False)
    super_manager = forms.CharField(label='super_manager', max_length=50, required=False)

class EditEmployeeForm(Form):
    id = forms.CharField(label='id', max_length=50)
    first_name = forms.CharField(label='first_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    email = forms.CharField(label='email', max_length=50, required=False)
    address = forms.CharField(label='address', max_length=100, required=False)
    tel_num = forms.CharField(label='tel_num', max_length=15, required=False)
    store = forms.CharField(label='store', max_length=50, required=False)

class CreateEmployeeForm(Form):
    login = forms.CharField(label='login', max_length=50)
    password = forms.CharField(label='password', max_length=50, min_length=6)
    first_name = forms.CharField(label='first_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    email = forms.CharField(label='email', max_length=50, required=False)
    address = forms.CharField(label='address',max_length=100, required=False)
    tel_num = forms.CharField(label='tel_num', max_length=15, required=False)
    store = forms.CharField(label='store', max_length=50, required=False)


class UserEditForm(Form):
    first_name = forms.CharField(label='firs_name', max_length=50, required=False)
    last_name = forms.CharField(label='last_name', max_length=50, required=False)
    email = forms.CharField(label='email', max_length=50, required=False)
    address = forms.CharField(max_length=100, required=False)
    tel_num = forms.CharField(max_length=15, required=False)

class ChangePasswordForm(Form):
    old_password = forms.CharField(label='old_password', max_length=50, min_length=6)
    new_password = forms.CharField(label='new_password', max_length=50, min_length=6)

class UserBorrowingForm(Form):
    store_id = forms.NumberInput()
    price = forms.NumberInput()
    duration = forms.NumberInput()
    event = forms.CharField(max_length=100, required=False)

costumes/templates/costumes/accessory.html
{% extends "base.html" %}

{% block title %}Accessory detail{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">{{accessory.name}}</h1>
  </div>
  <div class="row">
    <div class="col-sm">
      <img src="{{ accessory.picture.url }}" class="img-fluid" alt="Accessory image">
    </div>
    <div class="col-sm">
      <p>Description: {{accessory.description}}</p>
      <p>Price: {{accessory.price}} €</p>
      <p>Store: <a href="{% url 'stores' accessory.store.pk %}">{{accessory.store.city}} {{accessory.store.street}} {{accessory.store.num}}</a></p>
      <ul class="list-group mt-2">
	<li class="list-group-item list-group-item-dark">Best with costume:</li>
	{% for ct in accessory.belongs_to_costume.all %}
	    <li class="list-group-item"><a href="{% url 'costume_templates' ct.pk %}">{{ct.name}}</li>
	{% endfor %}
      </ul>
      <div class="my-2">
  {% if request.user.customer %}
    {% if accessory.id in request.session.basket_accessory %}
      <a class="btn btn-primary disabled" href="#" style="pointer-events: none; display: inline-block;" role="button">Already in basket</a>
    {% else %}
    {% if borrowed %}
    <a class="btn btn-warning disabled" role="button">Borrowed until {{ borrowed }}</a>
    {% else %}
      <a class="btn btn-primary" href="/add_accessory_to_basket?id={{ accessory.id }}" role="button">Add to basket</a>
    {% endif %}
    {% endif %}
  {% else %}
    {% if borrowed %}
    <a class="btn btn-warning disabled" role="button">Borrowed until {{ borrowed }}</a>
    {% endif %}
  {% endif %}
	{% if request.user.employee %}
	<a class="btn btn-success" href="{% url 'accessories_edit' accessory.pk %}" role="button">Edit</a>
  <a class="btn btn-danger" href="{% url 'accessories_delete' accessory.pk %}" role="button">Delete</a>
  {% endif %}
      </div>
    </div>
  </div>
  {% if request.user.employee %}
  <div class="row">
    <div class="col-sm">
      <ul class="list-group">
	<p class="list-group-item list-group-item-dark">Borrowings with this costume:</p>
	{% for borrowing in accessory.borrowing_set.all %}
	<li class="list-group-item"><a href="{% url 'borrowing' borrowing.pk %}">
	    Number: {{borrowing.pk}}
	    Event: {{borrowing.event}}
	    Costumes: {{borrowing.costume.all|length}}
	    Accesories: {{borrowing.accessory.all|length}}
	    From: {{borrowing.borrowed_date}}
	    To: {{borrowing.return_date}}
	</a></li>
	{% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

costumes/templates/costumes/accessory_card.html
<!-- TODO: On hover change color?-->
<!-- TODO: Width and size overall-->
<div class="col-lg-4 col-md-6 mb-4">
  <a href="{% url 'accessories' accessory.id %}">
    <div class="card h-100">
      <img class="card-img-top img-fluid" src="{{accessory.picture.url}}" alt="Card image cap">
      <div class="card-body">
	<h4 class="card-title">{{accessory.name}}</h4>
	<p class="card-text">Description: {{accessory.description}}</p>
      </div>
      <div class="card-footer">
	<p class="card-text">{{accessory.price}} €</small>
      </div>
    </div>
  </a>
</div>

costumes/templates/costumes/accessory_edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Accessory detail{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">{{accessory.name}}</h1>
  </div>
  <div class="col-lg-12">
    <form action="{% url 'accessories_edit' accessory.pk %}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Submit">Save</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/basket.html
{% extends "base.html" %}

{% block title %}Your shopping cart{% endblock %}

{% block content %}

<div class="container my-3">
    {% for costume in costumes.all %}
    <div class="row border-top border-bottom">
        <div class="col-3">
            <a href="{% url 'costumes' costume.id %}">
                <img class="card-img-top" src="{{costume.picture.url}}" alt="Card image cap" style="max-height: 100px; width: auto;">
            </a>
        </div>
        <div class="col my-auto">
            <h5 class="card-title">{{costume.costume_template.name}}</h5>
        </div>
        <div class="col my-auto">
            <h5 class="card-text">{{costume.price}} €</h5>
        </div>
        <div class="col my-auto">
            <h5 class="card-text">at: {{costume.store.street}}</h5>
        </div>
        <div class="col my-auto">
            <a class="btn btn-danger" href="/remove_costume_from_basket?id={{ costume.id }}" role="button">Remove from basket</a>
        </div>
      </div>
    {% endfor %}
    {% for accessory in accessory.all %}
    <div class="row border-top border-bottom">
        <div class="col-3">
            <a href="{% url 'accessories' accessory.id %}">
                <img class="card-img-top" src="{{accessory.picture.url}}" alt="Card image cap" style="max-height: 100px; width: auto;">
            </a>
        </div>
        <div class="col my-auto">
            <h5 class="align-middle">{{accessory.name}}</h5>
        </div>
        <div class="col my-auto">
            <h5 class="card-text">{{accessory.price}} €</h5>
        </div>
        <div class="col my-auto">
            <h5 class="card-text">at: {{accessory.store.street}}</h5>
        </div>
        <div class="col my-auto">
            <a class="btn btn-danger" href="/remove_accessory_from_basket?id={{ accessory.id }}" role="button">Remove from basket</a>
        </div>
      </div>
    {% endfor %}


    <div class="form-group" style="margin-top: 20px;">
    {% if has_items %}
        <form onsubmit="return confirm('Do you confirm this order ?');" method="POST" action="/finish_borrowing" >
        {% csrf_token %}
        <input hidden type="number" name="store_id" value="{{ store.id }}" class="form-control">
        <input hidden type="number" name="price" value="{{ total_price }}" class="form-control">
        <div class="form-group">
            <label>*Borrowing for number of days</label>
            <input type="number" name="duration" value="14" step="1" class="form-control" required>
        </div>
        <div class="form-group">
            <label>Event</label>
            <input type="text" name="event" class="form-control is-valid" placeholder="Describtion of event with these costumes">
        </div>
        <div class="form-group">
                <h5>Total price: {{ total_price }} €, located at: {{ store.street }}</h5>
        </div>
    {% endif %}
    <a class="btn btn-primary" style="margin-right: 10px;" href="/gallery" role="button">Back to gallery</a>
    {% if has_items %}
        {% if costumes_same_shop and accessory_same_shop %}
            <button class="btn btn-success" type="submit">Book costumes</button>
        {% else %}
            <a class="btn btn-danger disabled" role="button">Can't book costumes placed at differnet shops</a>
        {% endif %}
        </form>
    {% endif %}
    </div>
</div>

{% endblock %}

costumes/templates/costumes/costume_card.html
<div class="col-lg-4 col-md-6 mb-4">
  <a href="{% url 'costumes' costume.id %}">
    <div class="card h-100">
      <img class="card-img-top" src="{{costume.picture.url}}" alt="Card image cap">
      <div class="card-body">
	<h4 class="card-title">{{costume.costume_template.name}}</h4>
	<p class="card-text">Description: {{costume.costume_template.description}}</p>
      </div>
      <div class="card-footer">
	<p class="card-text">{{costume.price}} €</small>
      </div>
    </div>
  </a>
</div>

costumes/templates/costumes/costume_edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Costume detail{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">{{costume.costume_template.name}}</h1>
  </div>
  <div class="col-lg-12">
    <form action="{% url 'costumes_edit' costume.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Submit">Save</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/costume_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Add new costume{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">Create new costume</h1>
  </div>
  <div class="col-lg-12">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Save">Create</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/costume_template_edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Costume Template edit{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">Edit: {{ct.name}}</h1>
  </div>
  <div class="col-lg-12">
    <form action="{% url 'costume_templates_edit' ct.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Submit">Save</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/costume_templates_gallery.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}IIS - gallery{% endblock %}

{% block content %}
<div class="container my-3">
  <form action="" method="get" class="mt-2 mb-4">
    {% csrf_token %}
    {% bootstrap_form filter.form %}
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
  <ul class="list-group">
    <p class="list-group-item list-group-item-dark">Current costume templates in the system:</p>
    {% for costume_template in filter.qs %}
    <li class="list-group-item"><a href="{% url 'costume_templates' costume_template.pk %}">
	Name: {{costume_template.name}}
	Manufacturer: {{costume_template.manufacturer}}
	Material: {{costume_template.material}}
	Description: {{costume_template.description}}
    </a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

costumes/templates/costumes/show_user.html
{% extends "base.html" %}

{% block title %}IIS - Customers{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <div class="col-lg">
      <ul class="list-group">
	<p class="list-group-item list-group-item-dark">Customers in the system</p>
	{% for c in customers.all %}
	<li class="list-group-item"><a href="/user_detail/{{c.user.id}}">{{c.user.username}}: {{c.user.first_name}} {{c.user.last_name}}</a></li>
	{% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

costumes/templates/costumes/store_edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Store edit{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">Edit store</h1>
  </div>
  <div class="col-lg-12">
    <form action="{% url 'stores_edit' store.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Submit">Save</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/store_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}Add new costume{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">Add new store</h1>
  </div>
  <div class="col-lg-12">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary" type="submit" value="Save">Create</button>
    </form>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/stores.html
{% extends "base.html" %}

{% block title %}IIS - gallery{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <div class="col-lg">
      <ul class="list-group">
	<p class="list-group-item list-group-item-dark">Stores you can visit:</p>
	{% for store in stores.all %}
	<li class="list-group-item"><a href="{% url 'stores' store.pk %}">City {{store.city}} at {{store.street}} street</a></li>
	{% endfor %}
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-9 mt-2">
        {% for group in request.user.groups.all %}
        {% if group.name == "super_manager" %}
          <a class="btn btn-success" href="/add_store" role="button">Add new store</a>
        {% endif %}
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

costumes/templates/costumes/user_detail.html
{% extends "base.html" %}

{% block title %}User detail{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <h1 class="detail-site-header">User detail</h1>
  </div>
  <div class="row">

    <div class="col-sm">
      <p>Login: {{ customer.username }}</p>
      <p>First name: {{ customer.first_name }}</p>
      <p>Last name: {{ customer.last_name }}</p>
      <p>Email: {{ customer.email }}</p>
      <p>Address: {{ customer.customer.address }}</p>
      <p>Tel. num.: {{ customer.customer.tel_num }}</p>
    </div>
  </div>

  
  {% if request.user.manager %}
  <div style="margin-top: 20px;">
  <a class="btn btn-danger" onclick="return confirm('Do you want to delete customer: {{ customer.username }} ?')" href="/delete_user/{{customer.id}}" role="button">Delete</a>
  </div>
  {% endif %}
  
</div>
{% endblock %}